### ISSUE TITLE
Discuss including babel-plugin-add-module-exports

### ISSUE THREAD

**Issue by satazor** [moxystudio/babel-preset-moxy#5]
With our preset, we usually produce two builds:

`es/` - Contains ES modules and usually used by bundlers like webpack (enables treeshacking)
`lib/` - Contains CommonJS modules and usually used in Node.js

The issue is that, when on Node, we have to require modules like this:

```js
const myModule = require('my-module').default
```

This is kind of bad, see https://github.com/babel/babel/issues/2212 for more info.
To get around it, there's [babel-plugin-add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) that solves this.

Though, this can't be used in isomorphic applications, like react-with-moxy, because the same code must work on the server and on the client:

```
{
    // Will work on the client but not on the server
    // On the server, it would just be `require('./About')`
    component: require('./About').default,
}
```

We can choose between:
- Add the `add-module-exports` when `options.modules` is commonjs and add an option to not include this plugin so that we can disable it in isomorphic applications
- Keep it like this, which means that projects like [proper-url-join](https://github.com/moxystudio/js-proper-url-join/blob/aed170263c057124e40ae5de070e8435fcb9dfee/.babelrc#L5) must activate the plugin manually

I fear that 99% of the cases we want `add-module-exports`. What do you think?

**Comment by andregoncalvesdev** [comment]
`add-module-exports` +1

**Comment by andrefgneves** [comment]
I also vote on having the plugin (on for commonjs) and the option to disable it.

**Comment by satazor** [comment]
What should the name of the option be like?

**Comment by andrefgneves** [comment]
`namedDefaultExports`?

#### With the plugin enabled
```json
{ "presets": ["moxy", { "namedDefaultExports": false }] }
```

```js
const foo = require('./foo');
```

#### With the plugin disabled
```json
{ "presets": ["moxy", { "namedDefaultExports": true }] }
```

```js
const { default: foo } = require('./foo');
```
